{
  imports = [
    ./arr
    ./blocky.nix
    ./dashboard.nix
    ./firefox-syncserver.nix
    ./grafana.nix
    ./immich.nix
    ./jellyfin
    ./jellyseerr
    ./journald-loki.nix
    ./llama-cpp.nix
    ./pipewire
    ./qbittorrent.nix
    ./tailscale-funnel.nix
    ./tailscale-tls.nix
    ./vaultwarden.nix
  ];
}
